/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Newsletter } from "./Newsletter";
import { NewsletterCountArgs } from "./NewsletterCountArgs";
import { NewsletterFindManyArgs } from "./NewsletterFindManyArgs";
import { NewsletterFindUniqueArgs } from "./NewsletterFindUniqueArgs";
import { CreateNewsletterArgs } from "./CreateNewsletterArgs";
import { UpdateNewsletterArgs } from "./UpdateNewsletterArgs";
import { DeleteNewsletterArgs } from "./DeleteNewsletterArgs";
import { NewsletterService } from "../newsletter.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Newsletter)
export class NewsletterResolverBase {
  constructor(
    protected readonly service: NewsletterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Newsletter",
    action: "read",
    possession: "any",
  })
  async _newslettersMeta(
    @graphql.Args() args: NewsletterCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Newsletter])
  @nestAccessControl.UseRoles({
    resource: "Newsletter",
    action: "read",
    possession: "any",
  })
  async newsletters(
    @graphql.Args() args: NewsletterFindManyArgs
  ): Promise<Newsletter[]> {
    return this.service.newsletters(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Newsletter, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Newsletter",
    action: "read",
    possession: "own",
  })
  async newsletter(
    @graphql.Args() args: NewsletterFindUniqueArgs
  ): Promise<Newsletter | null> {
    const result = await this.service.newsletter(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Newsletter)
  @nestAccessControl.UseRoles({
    resource: "Newsletter",
    action: "create",
    possession: "any",
  })
  async createNewsletter(
    @graphql.Args() args: CreateNewsletterArgs
  ): Promise<Newsletter> {
    return await this.service.createNewsletter({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Newsletter)
  @nestAccessControl.UseRoles({
    resource: "Newsletter",
    action: "update",
    possession: "any",
  })
  async updateNewsletter(
    @graphql.Args() args: UpdateNewsletterArgs
  ): Promise<Newsletter | null> {
    try {
      return await this.service.updateNewsletter({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Newsletter)
  @nestAccessControl.UseRoles({
    resource: "Newsletter",
    action: "delete",
    possession: "any",
  })
  async deleteNewsletter(
    @graphql.Args() args: DeleteNewsletterArgs
  ): Promise<Newsletter | null> {
    try {
      return await this.service.deleteNewsletter(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
