/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { NewsletterService } from "../newsletter.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { NewsletterCreateInput } from "./NewsletterCreateInput";
import { Newsletter } from "./Newsletter";
import { NewsletterFindManyArgs } from "./NewsletterFindManyArgs";
import { NewsletterWhereUniqueInput } from "./NewsletterWhereUniqueInput";
import { NewsletterUpdateInput } from "./NewsletterUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class NewsletterControllerBase {
  constructor(
    protected readonly service: NewsletterService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Newsletter })
  @nestAccessControl.UseRoles({
    resource: "Newsletter",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createNewsletter(
    @common.Body() data: NewsletterCreateInput
  ): Promise<Newsletter> {
    return await this.service.createNewsletter({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        subject: true,
        content: true,
        recipients: true,
        sendDate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Newsletter] })
  @ApiNestedQuery(NewsletterFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Newsletter",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async newsletters(@common.Req() request: Request): Promise<Newsletter[]> {
    const args = plainToClass(NewsletterFindManyArgs, request.query);
    return this.service.newsletters({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        subject: true,
        content: true,
        recipients: true,
        sendDate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Newsletter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Newsletter",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async newsletter(
    @common.Param() params: NewsletterWhereUniqueInput
  ): Promise<Newsletter | null> {
    const result = await this.service.newsletter({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        subject: true,
        content: true,
        recipients: true,
        sendDate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Newsletter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Newsletter",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateNewsletter(
    @common.Param() params: NewsletterWhereUniqueInput,
    @common.Body() data: NewsletterUpdateInput
  ): Promise<Newsletter | null> {
    try {
      return await this.service.updateNewsletter({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          subject: true,
          content: true,
          recipients: true,
          sendDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Newsletter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Newsletter",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteNewsletter(
    @common.Param() params: NewsletterWhereUniqueInput
  ): Promise<Newsletter | null> {
    try {
      return await this.service.deleteNewsletter({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          subject: true,
          content: true,
          recipients: true,
          sendDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
